### ISSUE TITLE
How to use Map Maker

### ISSUE THREAD

**Issue by Starfunk** [carla-simulator/map#14]
I was just wondering if anyone can give a more detailed overview of how to use the Map Maker functionality.

In other words, given that I have an OSM map file that I want to convert to the adm format, what are the steps that I need to take? 

Any help would be greatly appreciated.

**Comment by berndgassmann** [comment]
If you have build the osm_to_adm tool, and downloaded the osm file, then just executing the tool on the osm file; e.g.:
osm_to_adm MyDownloadedMap.osm -o MyDownloadedMap.adm -t secondary,tertiary,residential

You might have to set the LD_LIBRARY_PATH before:
export LD_LIBRARY_PATH=install/ad_physics/lib:install/ad_map_access/lib:install/ad_map_opendrive_reader/lib

Or you build it with the static colcon configuration to get rid of the LD_LIBRARY_PATH:
colcon build --metas colcon_static_qgis.meta --packages-up-to MapMaker --build-base build-static --install-base install-static
Then you can omit the LD_LIBRARY_PATH and call it directly
./install-static/MapMaker/bin/osm_to_adm

Maybe we should remove the 'qgis' suffix from the meta file since it's not actually QGIS specific...

For more options on conversion, you can just call
./install-static/MapMaker/bin/osm_to_adm --help

But I see, there is room for improvement of the docu in respect to this; so let's keep this issue open until we improved the docu around this.

Thanks for asking,
If you encounter any further issues, please tell us...

Bernd.
