### ISSUE TITLE
Does planRoute support finding route across different roads?

### ISSUE THREAD

**Issue by tin1254** [carla-simulator/map#26]
Hi, I find a [video](https://youtu.be/UxKPXPT2T8Q?t=92) from you guys last year, it said only a situation within the same road segment is supported.

My question is, does it support different road segments now? I couldn't find any documentation about this issue.
 
I tested `ad::map::route::planning::planRoute` on [my custom map](https://github.com/bark-simulator/bark/blob/master/bark/runtime/tests/data/DR_CHN_Merging_ZS_partial_v02.xodr), and it always returns an empty route if it has supporting points across two roads.

**Comment by berndgassmann** [comment]
Hi,

since CARLA 0.9.9 the full road is supported for the RSS Sensor (see details: http://carla.org/2020/04/22/release-0.9.9/#rss-full-road-integration).
This library laid the basis for this feature. So in this library full road is supported ever since.

You could try to compile the QGIS plugin and load your map in the QGIS tool with the AD-Map plugin; then you directly can test the routing capabilitites on the fly...

![QGIs-screenshot](https://user-images.githubusercontent.com/44812003/93092078-440a9a80-f69f-11ea-83fc-77716a4c15ed.PNG)
 
I loaded the map there and routing works fine. Do you consider the right routing direction (order of the routing points)?

![QGis-Screenshot-LaneIds](https://user-images.githubusercontent.com/44812003/93092665-04907e00-f6a0-11ea-8108-501d6dfcd737.PNG)

When I enable lane ID listing and zoom in then all looks fine to me.

::ad::map::route::planning::planRoute(::ad::map::point::createParaPoint(::ad::map::lane::LaneId(147), ad::physics::ParametricValue(0.2)), ::ad::map::point::createParaPoint(::ad::map::lane::LaneId(10149), ad::physics::ParametricValue(0.8)))

Should provide a valid route.

![QGis-Ids](https://user-images.githubusercontent.com/44812003/93093374-e7a87a80-f6a0-11ea-8b9b-0886a066f935.png)

Or you maybe use the non-Normal lanes (146 or 10147) for the routing start/end? These won't work.

**Comment by berndgassmann** [comment]
You can also have a look into
https://github.com/carla-simulator/map/blob/master/ad_map_access/impl/tests/route/RoutePlanningTests.cpp

where `lane::uniqueLaneId()` is used to get the point from GeoCoordinates or recently the `uniqueParaPoint()` was added, which already provides the parameticPoint of a geo-coordinate https://ad-map-access.readthedocs.io/en/latest/ad_map_access/apidoc/html/namespacead_1_1map_1_1lane.html#a6f6e6c33bc6b5fc803f6b055c22c7b3f

This for sure only works if there is actually a unique lane below the point (especially will not work within intersections where lane overlap each other ... but such is not present in your map...).

```
auto startParaPoint = ad::map::lane::uniqueParaPoint(ad::map::point::createGeoPoint(ad::map::point::Longitude(0.009193),
                                          ad::map::point::Latitude(0.008705),
                                          ad::map::point::Altitude(0.)));
auto endParaPoint = ad::map::lane::uniqueParaPoint(ad::map::point::createGeoPoint(ad::map::point::Longitude(0.010258),
                                          ad::map::point::Latitude(0.008638),
                                          ad::map::point::Altitude(0.)));
```

From QGis coordinate listing in the lower toolbar the two points should roughly provide points within 147 and 10149...

**Comment by tin1254** [comment]
Thanks for the detailed response! @berndgassmann 
I checked my route with QGIS, and the issue was I created supporting routing points at the end of lane 147. And because it is so narrow at the end, some of points were identified as within 146 or 10147. This can be solved by providing just one geo point as the goal.
