### ISSUE TITLE
'ad_map_access_qgis_python' not available in 'tools' folder

### ISSUE THREAD

**Issue by lrstttl** [carla-simulator/map#65]
Hi all,

the documentation for the plain CMake build of the QGIS plugin (https://ad-map-access.readthedocs.io/en/latest/BUILDING/) contains the following steps:
```
map$> cd build/ad_map_access_qgis_python
map/build/ad_map_access_qgis_python$> cmake ../../tools/ad_map_access_qgis_python -DCMAKE_INSTALL_PREFIX=../../install/ad_map_access_qgis_python -DCMAKE_PREFIX_PATH="../../install/proj;../../install/spdlog;../../install/ad_physics;../../install/ad_map_opendrive_reader;../../install/ad_map_access"
map/build/ad_map_access_qgis_python$> make install
```
However, in the tools folder (https://github.com/carla-simulator/map/tree/master/tools), there is no folder called `ad_map_access_qgis_python`. 

Did I miss something in the documentation?

**Comment by berndgassmann** [comment]
Hi,
You are right, that is not available anymore since we had added auto-generated python binding of the C++ library.
Will delete this from the docu.

If you want to test the QGIS plugin, you can directly download it from the release.
We've also just recognized, that you then will have to install the python packages of the C++ libraries via pip (see https://pypi.org/project/ad-map-access/).

**Comment by berndgassmann** [comment]
In each case, I would prefer to use colcon to build. Manual cmake steps are tedious and error prone.
