### ISSUE TITLE
Missing metadata file when build a plugin

### ISSUE THREAD

**Issue by gintingmanik** [carla-simulator/map#83]
Hi,
I try to build a plugin on QGIS 3 for my Research but got trouble when load the plugin form Manage and Install Plugin menu. I've saved the plugin on C:\Users\Mineplan3\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
please teach me how to solve this
![github](https://user-images.githubusercontent.com/107456692/198944844-7af5fcf4-a0f2-4dce-a50a-c87de6876c7f.png)

**Comment by berndgassmann** [comment]
You might be asking because we also provide a plugin for qgis with our map, so I only can provide you with the example of our plguin here:
https://github.com/carla-simulator/map/blob/master/tools/ad_map_access_qgis/
you need a metafile (which might be missing in your case) like e.g. our
https://github.com/carla-simulator/map/blob/master/tools/ad_map_access_qgis/metadata.txt.in

or you download our build zip file from here (where the metafile is actually there as metadata.txt):
https://github.com/carla-simulator/map/releases/tag/v2.6.2

Other than that, you have to check on QGIS community on how to solve your concrete problem in more detail, I fear. We are also only users of QGIS :-)
