### ISSUE TITLE
Generation of Carla Maps

### ISSUE THREAD

**Issue by WilliaJing** [carla-simulator/map#86]
Hi,Are official Carla maps, such as town01 and town02, edited and exported by Roadrunner? What is the version used for that?
I hope you can provide me with some logic generated by carla map. Thank you very much.

**Comment by berndgassmann** [comment]
Hi, I believe so, but I can't tell you exactly since the content of this repo is not yet deployed within carla 1:1; and I'm not involved in the map creation. The opendrive reader in here is based on the code from carla. And this repo provides the QGis Plugin for maps which is also the basis for the [scenario edior](https://github.com/carla-simulator/traffic-generation-editor).
But the information you are searching is written in the xodr files header of the maps themselves ;-)
Town03.xodr was created with RoadRunner 2019.2.12. Town10HD_Opt.xodr, too.
But I was lately working with RoadRunner 2023a on my end for some project to edit a map, which also works as a charme.
I guess you should look at https://carla.readthedocs.io/en/latest/tuto_content_authoring_maps/ to get more details.
Sorry for the very late answer to this. But better late than never -- in case someone else wants an answer.
